# ----------- Build Stage -----------
FROM node:20-alpine AS builder

WORKDIR /app

# Copy only package files first for caching
COPY package*.json ./

# Install all dependencies (including devDependencies for build)
RUN npm install

# Copy the rest of the source code
COPY . .

CMD ["npm", "run", "dev"]
